# a curated list of available hooks
# https://pre-commit.com/hooks.html
minimum_pre_commit_version: '3.2'

exclude: (\.fits|\.fits\.gz|\.oifits)$

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.10.0
  hooks:
  - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: 1.18.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.9.1]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
